
  CREATE TABLE "C##EVOLVICE"."CAR" 
   (	"CAR_ID" NUMBER(5,0) NOT NULL ENABLE, 
	"BRAND" VARCHAR2(30 BYTE) NOT NULL ENABLE, 
	"MODEL" VARCHAR2(30 BYTE) NOT NULL ENABLE, 
	"YEAR_OF_PRODUCTION" VARCHAR2(4 BYTE) NOT NULL ENABLE, 
	"CATEGORY" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	 CONSTRAINT "TABLE1_PK" PRIMARY KEY ("CAR_ID")
   )  ;

   CREATE SEQUENCE  "C##EVOLVICE"."CAR_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;